services:
  server:
    build: ./Server
    image: server:latest
    container_name: server
    env_file:
      - .env
    ports:
      - "9090:9090"
      - "9000:9000"
    depends_on:
      - db
      - analyzer
    networks:
      - network
    command: sh /app/entrypoint.sh

  client:
    build: ./Client
    image: client:latest
    container_name: client
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - server
    networks:
      - network

  analyzer:
    build: ./Analyzer
    image: analyzer:latest
    container_name: analyzer
    ports:
      - "9091:9090"
    networks:
      - network

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/data
    networks:
      - network

  redis:
    image: redis:7.4.1
    container_name: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    command: >
      redis-server --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:  
    driver: local
