services:
  server:
    build: .
    image: server:latest
    container_name: server
    env_file:
      - .env
    ports:
      - "9090:9090"
      - "9000:9000"
    depends_on:
      - db
    networks:
      - server_network
    command: sh /app/entrypoint.sh

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - server_network

  redis:
    image: redis:7.4.1
    container_name: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    command: >
      redis-server --requirepass "${REDIS_PASSWORD}"
    networks:
      - server_network

networks:
  server_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
